export type ExerciseCategory = "vocabulary" | "grammar" | "communication" | "reading" | "listening" | "speaking";
export type ExerciseStatus = "active" | "coming_soon";
export type ExerciseMode = "multiple-choice" | "fill-gap" | "writing" | "reading" | "listening" | "speaking";

export type ExerciseDefinition = {
  id: string;
  category: ExerciseCategory;
  mode: ExerciseMode;
  name: string;
  description: string;
  rule: string;
  examplePrompt: string;
  exampleAnswer: string;
  status: ExerciseStatus;
};

export const EXERCISE_MODES: Array<{ id: ExerciseMode; name: string }> = [
  { id: "multiple-choice", name: "Opción múltiple" },
  { id: "fill-gap", name: "Completar huecos" },
  { id: "writing", name: "Escritura" },
  { id: "reading", name: "Lectura" },
  { id: "listening", name: "Escucha" },
  { id: "speaking", name: "Habla" },
];

export const EXERCISE_PRESETS: Array<{ id: string; name: string; description: string; modes: ExerciseMode[] }> = [
  { id: "quick", name: "Rápido y fácil", description: "Opciones y huecos, sin escribir demasiado.", modes: ["multiple-choice", "fill-gap"] },
  { id: "public", name: "En público", description: "Práctica silenciosa sin escuchar ni hablar.", modes: ["multiple-choice", "fill-gap", "writing", "reading"] },
  { id: "hands-free", name: "Manos libres", description: "Solo comprensión auditiva y expresión oral.", modes: ["listening", "speaking"] },
];

export const EXERCISE_CATEGORIES: Array<{ id: ExerciseCategory; name: string; description: string }> = [
  { id: "vocabulary", name: "Vocabulario", description: "Recordar, distinguir y usar palabras y combinaciones." },
  { id: "grammar", name: "Gramática", description: "Formar, elegir y aplicar estructuras con intención." },
  { id: "communication", name: "Comunicación", description: "Resolver situaciones reales con lenguaje natural." },
  { id: "reading", name: "Lectura", description: "Comprender ideas, detalles, relaciones y mensajes." },
  { id: "listening", name: "Comprensión auditiva", description: "Entender español hablado sin depender del texto." },
  { id: "speaking", name: "Expresión oral", description: "Convertir conocimiento en habla comprensible y fluida." },
];

export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: "written-recall",
    category: "vocabulary",
    mode: "writing",
    name: "Recuerdo escrito",
    description: "Recupera el significado sin verlo entre opciones.",
    rule: "Siempre se escribe una respuesta; nunca se revela después de pensarlo solamente.",
    examplePrompt: "anhelo",
    exampleAnswer: "Sehnsucht / Wunsch",
    status: "active",
  },
  {
    id: "active-translation",
    category: "vocabulary",
    mode: "writing",
    name: "Traducción activa",
    description: "Pasa del alemán al español para activar el vocabulario.",
    rule: "Los sustantivos incluyen artículo y los verbos conservan su complemento: hablar con, ir a.",
    examplePrompt: "die Freundschaft",
    exampleAnswer: "la amistad",
    status: "active",
  },
  {
    id: "reverse-translation",
    category: "vocabulary",
    mode: "writing",
    name: "Traducción inversa",
    description: "Comprende una forma española sin opciones.",
    rule: "Se aceptan sinónimos alemanes que conservan el significado.",
    examplePrompt: "alojarse en",
    exampleAnswer: "übernachten in / unterkommen in",
    status: "active",
  },
  {
    id: "vocabulary-gap",
    category: "vocabulary",
    mode: "fill-gap",
    name: "Completa con la palabra",
    description: "Recupera vocabulario a partir de un contexto suficiente.",
    rule: "La frase debe dejar clara la respuesta o aceptar todas las alternativas naturales.",
    examplePrompt: "Durante el viaje nos vamos a ___ en un hotel pequeño.",
    exampleAnswer: "alojar",
    status: "active",
  },
  {
    id: "collocations",
    category: "vocabulary",
    mode: "fill-gap",
    name: "Colocaciones y expresiones",
    description: "Aprende palabras junto con sus preposiciones y compañeros habituales.",
    rule: "Los verbos se practican como hablar con, depender de o ir a; no como infinitivos aislados.",
    examplePrompt: "Gracias ___ la invitación.",
    exampleAnswer: "por",
    status: "active",
  },
  {
    id: "lexical-contrast",
    category: "vocabulary",
    mode: "multiple-choice",
    name: "Palabras parecidas",
    description: "Distingue palabras cercanas que suelen confundirse.",
    rule: "Todas las opciones pertenecen al mismo campo semántico y son plausibles.",
    examplePrompt: "La mesa está en la ___ de la habitación. ¿esquina o rincón?",
    exampleAnswer: "esquina",
    status: "active",
  },
  {
    id: "own-sentence",
    category: "vocabulary",
    mode: "writing",
    name: "Escribe una frase",
    description: "Usa una palabra o combinación en una idea propia.",
    rule: "El estímulo es una palabra o combinación breve, nunca una frase ya completa.",
    examplePrompt: "Escribe una frase con «aburrimiento».",
    exampleAnswer: "El aburrimiento me hizo salir a dar un paseo.",
    status: "active",
  },
  {
    id: "conjugation-dice",
    category: "grammar",
    mode: "writing",
    name: "Dado de conjugación",
    description: "Recupera una forma verbal a partir de persona y tiempo.",
    rule: "El verbo conserva su preposición o complemento cuando lo necesita.",
    examplePrompt: "hablar con · yo · presente",
    exampleAnswer: "hablo con",
    status: "active",
  },
  {
    id: "conjugation-context",
    category: "grammar",
    mode: "fill-gap",
    name: "Conjugación en contexto",
    description: "Forma el verbo que exige una situación real.",
    rule: "El contexto indica claramente persona, tiempo y complemento.",
    examplePrompt: "Si tuviera más tiempo, ___ más con mis vecinos. (hablar con)",
    exampleAnswer: "hablaría",
    status: "active",
  },
  {
    id: "sentence-transformation",
    category: "grammar",
    mode: "writing",
    name: "Transforma la frase",
    description: "Cambia una forma sin perder el significado principal.",
    rule: "La instrucción especifica exactamente qué debe cambiar.",
    examplePrompt: "Pasa al condicional: «Te ayudo con la mesa».",
    exampleAnswer: "Te ayudaría con la mesa.",
    status: "active",
  },
  {
    id: "pronoun-substitution",
    category: "grammar",
    mode: "writing",
    name: "Sustituye por pronombres",
    description: "Convierte objetos explícitos en pronombres correctos.",
    rule: "La respuesta conserva persona, número y orden de los pronombres.",
    examplePrompt: "Pedro ha regalado las rosas a la abuela. Sustituye los objetos.",
    exampleAnswer: "Pedro se las ha regalado.",
    status: "active",
  },
  {
    id: "grammar-choice",
    category: "grammar",
    mode: "multiple-choice",
    name: "Elige la forma adecuada",
    description: "Toma una decisión gramatical por su significado.",
    rule: "Las opciones representan un contraste real y no formas aleatorias.",
    examplePrompt: "Tengo vino blanco y tinto. ¿___ quieres?",
    exampleAnswer: "Cuál",
    status: "active",
  },
  {
    id: "error-correction",
    category: "grammar",
    mode: "writing",
    name: "Corrige el error",
    description: "Detecta y repara un error habitual de la regla actual.",
    rule: "Cada frase contiene un solo problema relevante para el objetivo.",
    examplePrompt: "Corrige: «Le lo he regalado».",
    exampleAnswer: "Se lo he regalado.",
    status: "active",
  },
  {
    id: "sentence-order",
    category: "grammar",
    mode: "writing",
    name: "Ordena la frase",
    description: "Reconstruye el orden natural del español.",
    rule: "Solo se usa cuando existe un orden claramente defendible.",
    examplePrompt: "se / las / ha regalado / Pedro",
    exampleAnswer: "Pedro se las ha regalado.",
    status: "active",
  },
  {
    id: "complete-rule",
    category: "grammar",
    mode: "fill-gap",
    name: "Completa la regla",
    description: "Recuerda de forma explícita cómo funciona una estructura.",
    rule: "Aporta menos evidencia que usar la regla y aparece con moderación.",
    examplePrompt: "En el condicional, las terminaciones se añaden al ___.",
    exampleAnswer: "infinitivo",
    status: "active",
  },
  {
    id: "guided-production",
    category: "grammar",
    mode: "writing",
    name: "Producción guiada",
    description: "Expresa una intención usando una regla concreta.",
    rule: "La situación y la restricción están claras, pero la frase no viene dada.",
    examplePrompt: "Pide agua cortésmente usando el condicional.",
    exampleAnswer: "¿Podrías traerme un poco de agua?",
    status: "active",
  },
  {
    id: "dialogue-completion",
    category: "communication",
    mode: "fill-gap",
    name: "Completa el diálogo",
    description: "Combina vocabulario y gramática en una conversación.",
    rule: "Se aceptan todas las respuestas naturales que cumplen la función comunicativa.",
    examplePrompt: "—¿Te apetece venir a mi fiesta?\n—___",
    exampleAnswer: "Me encantaría, pero tengo un compromiso.",
    status: "active",
  },
  {
    id: "appropriate-response",
    category: "communication",
    mode: "multiple-choice",
    name: "Elige la reacción adecuada",
    description: "Selecciona una respuesta natural para una situación.",
    rule: "Todas las opciones son respuestas verosímiles del mismo tipo.",
    examplePrompt: "Un amigo te da un regalo inesperado. ¿Qué dices?",
    exampleAnswer: "Gracias, ¡qué detalle!",
    status: "active",
  },
  {
    id: "contextual-translation",
    category: "communication",
    mode: "writing",
    name: "Traducción contextual",
    description: "Transmite una intención de forma natural, no palabra por palabra.",
    rule: "La evaluación es semántica y la referencia es solo un ejemplo.",
    examplePrompt: "Ich würde gerne kommen, aber ich habe schon etwas vor.",
    exampleAnswer: "Me gustaría ir, pero ya tengo planes.",
    status: "active",
  },
  {
    id: "reading-main-idea",
    category: "reading",
    mode: "reading",
    name: "Idea principal",
    description: "Comprende el propósito general sin traducir todo.",
    rule: "El texto es breve, original y reutiliza contenido del curso.",
    examplePrompt: "Marta celebra su cumpleaños el sábado. Ana quiere ir, pero trabaja. ¿Cuál es la idea principal?",
    exampleAnswer: "Ana no puede asistir y propone otro momento.",
    status: "active",
  },
  {
    id: "reading-detail",
    category: "reading",
    mode: "reading",
    name: "Detalles e inferencias",
    description: "Encuentra información y saca una conclusión razonable.",
    rule: "La explicación distingue lo dicho de lo inferido.",
    examplePrompt: "Ana propone quedar el domingo porque el sábado trabaja. ¿Por qué elige el domingo?",
    exampleAnswer: "Porque el sábado tiene que trabajar.",
    status: "active",
  },
  {
    id: "reading-reference",
    category: "reading",
    mode: "reading",
    name: "Referencias y conectores",
    description: "Identifica pronombres y relaciones entre ideas.",
    rule: "La referencia tiene un antecedente inequívoco en el texto.",
    examplePrompt: "Marta invitó a Ana, pero ella no podía asistir. ¿Quién es «ella»?",
    exampleAnswer: "Ana",
    status: "active",
  },
  {
    id: "reading-order",
    category: "reading",
    mode: "reading",
    name: "Reconstruye el texto",
    description: "Ordena acontecimientos usando lógica y conectores.",
    rule: "El texto contiene pistas suficientes para un solo orden principal.",
    examplePrompt: "1 Finalmente quedamos el domingo. 2 Marta me invitó. 3 Sin embargo, el sábado trabajaba.",
    exampleAnswer: "2 → 3 → 1",
    status: "active",
  },
  {
    id: "reading-mediation",
    category: "reading",
    mode: "reading",
    name: "Resume o transmite",
    description: "Conserva la información esencial al explicarla a otra persona.",
    rule: "Se evalúa la información preservada, no la copia literal.",
    examplePrompt: "La clase empieza a las diez en vez de a las nueve. Erkläre kurz, was sich geändert hat.",
    exampleAnswer: "Der Unterricht beginnt morgen erst um zehn Uhr.",
    status: "active",
  },
  {
    id: "listening-main-idea",
    category: "listening",
    mode: "listening",
    name: "Escucha: idea general",
    description: "Identifica situación, propósito o intención.",
    rule: "Primera escucha sin transcripción.",
    examplePrompt: "Audio: «¿Te apetece venir a cenar el viernes?»",
    exampleAnswer: "Invita a alguien a cenar.",
    status: "coming_soon",
  },
  {
    id: "listening-detail",
    category: "listening",
    mode: "listening",
    name: "Escucha: información concreta",
    description: "Extrae una hora, razón, persona o dato.",
    rule: "El audio completo se oye antes de ofrecer ayudas.",
    examplePrompt: "Audio: «Llegaré media hora después de las ocho». ¿A qué hora llega?",
    exampleAnswer: "A las ocho y media.",
    status: "coming_soon",
  },
  {
    id: "selective-dictation",
    category: "listening",
    mode: "listening",
    name: "Dictado selectivo",
    description: "Conecta sonido, ortografía y forma gramatical.",
    rule: "Usa fragmentos breves y significativos.",
    examplePrompt: "Audio: «Me gustaría ir, pero tengo un compromiso».",
    exampleAnswer: "Me gustaría ir, pero tengo un compromiso.",
    status: "coming_soon",
  },
  {
    id: "sound-contrast",
    category: "listening",
    mode: "listening",
    name: "Distingue lo que oyes",
    description: "Diferencia formas cercanas en habla natural.",
    rule: "Solo contrasta formas que realmente puedan confundirse.",
    examplePrompt: "Audio: «hablo». ¿hablo o habló?",
    exampleAnswer: "hablo",
    status: "coming_soon",
  },
  {
    id: "repeat-and-compare",
    category: "speaking",
    mode: "speaking",
    name: "Repite y compara",
    description: "Practica pronunciación, acento y ritmo.",
    rule: "Prioriza la inteligibilidad, no un acento nativo.",
    examplePrompt: "¿Podrías ayudarme a poner la mesa?",
    exampleAnswer: "Acento claro en «podrías».",
    status: "coming_soon",
  },
  {
    id: "quick-response",
    category: "speaking",
    mode: "speaking",
    name: "Respuesta rápida",
    description: "Responde con lenguaje conocido sin preparación larga.",
    rule: "Acepta varias respuestas naturales.",
    examplePrompt: "¿Te apetece algo para beber?",
    exampleAnswer: "Sí, un poco de agua, por favor.",
    status: "coming_soon",
  },
  {
    id: "oral-transformation",
    category: "speaking",
    mode: "speaking",
    name: "Transformación oral",
    description: "Cambia una forma gramatical en voz alta.",
    rule: "Solo cambia el rasgo indicado.",
    examplePrompt: "«Voy a la fiesta». Exprésalo en condicional.",
    exampleAnswer: "Iría a la fiesta.",
    status: "coming_soon",
  },
  {
    id: "role-play",
    category: "speaking",
    mode: "speaking",
    name: "Situación o juego de rol",
    description: "Resuelve una situación comunicativa real.",
    rule: "El éxito comunicativo pesa más que los errores secundarios.",
    examplePrompt: "Rechaza cortésmente una invitación y da una razón.",
    exampleAnswer: "Gracias, pero no puedo ir porque tengo que trabajar.",
    status: "coming_soon",
  },
  {
    id: "oral-summary",
    category: "speaking",
    mode: "speaking",
    name: "Cuenta o resume",
    description: "Produce varias frases conectadas.",
    rule: "Empieza con veinte segundos y repite una tarea parecida más adelante.",
    examplePrompt: "Cuenta qué hiciste el fin de semana con dos verbos en pasado.",
    exampleAnswer: "El sábado fui al mercado y después comí con unos amigos.",
    status: "coming_soon",
  },
];

export const ACTIVE_EXERCISE_IDS = EXERCISE_LIBRARY
  .filter((exercise) => exercise.status === "active")
  .map((exercise) => exercise.id);

export function isActiveExerciseId(value: unknown): value is string {
  return typeof value === "string" && ACTIVE_EXERCISE_IDS.includes(value);
}
